#debug=true
spring.datasource.url=jdbc:postgresql://localhost:5432/film_archive
spring.datasource.username=filmApp
spring.datasource.password=filmapp2026**

spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false