# Thymeleaf template cache
spring.thymeleaf.cache=false

# Static resource cache
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

# Read templates directly from source during development
spring.thymeleaf.prefix=file:src/main/resources/templates/

# Read CSS / JS / images directly from source during development
spring.web.resources.static-locations=file:src/main/resources/static/