CREATE TABLE films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    imdb_id VARCHAR(20) NOT NULL,
    title VARCHAR(300) NOT NULL,

    year_text VARCHAR(30),
    release_year SMALLINT,

    type VARCHAR(20),

    released_on DATE,
    runtime_minutes SMALLINT,

    genres_text VARCHAR(500),

    director VARCHAR(500),
    actors VARCHAR(1000),

    plot TEXT,
    poster_url TEXT,

    imdb_rating NUMERIC(3,1),

    fetched_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_films_imdb_id UNIQUE (imdb_id)
);

CREATE INDEX idx_films_release_year
    ON films(release_year);

CREATE INDEX idx_films_type
    ON films(type);
