CREATE TABLE user_films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,
    film_id BIGINT NOT NULL,

    added_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_user_films_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_user_films_film
        FOREIGN KEY (film_id)
        REFERENCES films(id),

    CONSTRAINT uk_user_films_user_film
        UNIQUE (user_id, film_id)
);

CREATE INDEX idx_user_films_user_added_at
    ON user_films(user_id, added_at DESC);
